/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";
import { PALLETURL } from "../../constant/pallet";
import convertToWarehouseSize from "../../utilityFunc/convertToWarehouseSize";
import defaultPositionPallet from "../../utilityFunc/defaultPositionPallet";
import convertPosToReaclPos from "../../utilityFunc/convertPosToReaclPos";

export default function Pallet401534Scene({
  warehouseSize,
  useCamera,
  positionPallet,
}) {
  const { nodes, materials } = useSpline(PALLETURL);
  const size = convertToWarehouseSize(warehouseSize);
  let defPos = defaultPositionPallet(Object.values(size), [40, 15, 34]);
  const position = convertPosToReaclPos(positionPallet);
  console.log("defPos: ", defPos);
  console.log("position: ", position);
  return (
    <>
      {nodes && materials && (
        <group
          name="Pallet_40-15-34"
          position={[
            defPos[0] + position[0],
            defPos[1] + position[2],
            defPos[2] + position[1],
          ]}
        >
          <group name="GroupX1" position={[0, 1, 0]}>
            <mesh
              name="CubeX_1-11"
              geometry={nodes["CubeX_1-11"].geometry}
              material={materials["CubeX_1-11 Material"]}
              castShadow
              receiveShadow
              position={[0, 16.5, -7]}
            />
            <mesh
              name="CubeX_1-21"
              geometry={nodes["CubeX_1-21"].geometry}
              material={materials["CubeX_1-21 Material"]}
              castShadow
              receiveShadow
              position={[0, 6.1, -7]}
            />
            <mesh
              name="CubeX_1-31"
              geometry={nodes["CubeX_1-31"].geometry}
              material={materials["CubeX_1-31 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.2, -7]}
            />
            <mesh
              name="CubeX_1-4"
              geometry={nodes["CubeX_1-4"].geometry}
              material={materials["CubeX_1-4 Material"]}
              castShadow
              receiveShadow
              position={[0, -16.5, -7]}
            />
            <mesh
              name="CubeX_2-11"
              geometry={nodes["CubeX_2-11"].geometry}
              material={materials["CubeX_2-11 Material"]}
              castShadow
              receiveShadow
              position={[0, 16.5, 0]}
            />
            <mesh
              name="CubeX_2-21"
              geometry={nodes["CubeX_2-21"].geometry}
              material={materials["CubeX_2-21 Material"]}
              castShadow
              receiveShadow
              position={[0, 6.1, 0]}
            />
            <mesh
              name="CubeX_2-31"
              geometry={nodes["CubeX_2-31"].geometry}
              material={materials["CubeX_2-31 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.2, 0]}
            />
            <mesh
              name="CubeX_2-4"
              geometry={nodes["CubeX_2-4"].geometry}
              material={materials["CubeX_2-4 Material"]}
              castShadow
              receiveShadow
              position={[0, -16.5, 0]}
            />
            <mesh
              name="CubeX_3-11"
              geometry={nodes["CubeX_3-11"].geometry}
              material={materials["CubeX_3-11 Material"]}
              castShadow
              receiveShadow
              position={[0, 16.5, 7]}
            />
            <mesh
              name="CubeX_3-21"
              geometry={nodes["CubeX_3-21"].geometry}
              material={materials["CubeX_3-21 Material"]}
              castShadow
              receiveShadow
              position={[0, 6.1, 7]}
            />
            <mesh
              name="CubeX_3-31"
              geometry={nodes["CubeX_3-31"].geometry}
              material={materials["CubeX_3-31 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.2, 7]}
            />
            <mesh
              name="CubeX_3-4"
              geometry={nodes["CubeX_3-4"].geometry}
              material={materials["CubeX_3-4 Material"]}
              castShadow
              receiveShadow
              position={[0, -16.5, 7]}
            />
          </group>
          <group name="GroupY1" position={[0, 1, 0]}>
            <mesh
              name="CubeY_1-11"
              geometry={nodes["CubeY_1-11"].geometry}
              material={materials["CubeY_1-11 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, -1, -7]}
            />
            <mesh
              name="CubeY_1-21"
              geometry={nodes["CubeY_1-21"].geometry}
              material={materials["CubeY_1-21 Material"]}
              castShadow
              receiveShadow
              position={[0, -1, -7]}
            />
            <mesh
              name="CubeY_1-31"
              geometry={nodes["CubeY_1-31"].geometry}
              material={materials["CubeY_1-31 Material"]}
              castShadow
              receiveShadow
              position={[19.5, -1, -7]}
            />
            <mesh
              name="CubeY_2-1"
              geometry={nodes["CubeY_2-1"].geometry}
              material={materials["CubeY_2-1 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, -1, 7]}
            />
            <mesh
              name="CubeY_2-21"
              geometry={nodes["CubeY_2-21"].geometry}
              material={materials["CubeY_2-21 Material"]}
              castShadow
              receiveShadow
              position={[0, -1, 7]}
            />
            <mesh
              name="CubeY_2-31"
              geometry={nodes["CubeY_2-31"].geometry}
              material={materials["CubeY_2-31 Material"]}
              castShadow
              receiveShadow
              position={[19.5, -1, 7]}
            />
          </group>
          <group name="GroupZ1" position={[0, 1, 0]}>
            <mesh
              name="CubeZ_1-11"
              geometry={nodes["CubeZ_1-11"].geometry}
              material={materials["CubeZ_1-11 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, 16.5, 0]}
            />
            <mesh
              name="CubeZ_2-11"
              geometry={nodes["CubeZ_2-11"].geometry}
              material={materials["CubeZ_2-11 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, 6.1, 0]}
            />
            <mesh
              name="CubeZ_3-11"
              geometry={nodes["CubeZ_3-11"].geometry}
              material={materials["CubeZ_3-11 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, -5.2, 0]}
            />
            <mesh
              name="CubeZ_4-1"
              geometry={nodes["CubeZ_4-1"].geometry}
              material={materials["CubeZ_4-1 Material"]}
              castShadow
              receiveShadow
              position={[-19.5, -16.5, 0]}
            />
            <mesh
              name="CubeZ_1-21"
              geometry={nodes["CubeZ_1-21"].geometry}
              material={materials["CubeZ_1-21 Material"]}
              castShadow
              receiveShadow
              position={[0, 16.5, 0]}
            />
            <mesh
              name="CubeZ_2-21"
              geometry={nodes["CubeZ_2-21"].geometry}
              material={materials["CubeZ_2-21 Material"]}
              castShadow
              receiveShadow
              position={[0, 6.1, 0]}
            />
            <mesh
              name="CubeZ_3-21"
              geometry={nodes["CubeZ_3-21"].geometry}
              material={materials["CubeZ_3-21 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.2, 0]}
            />
            <mesh
              name="CubeZ_4-2"
              geometry={nodes["CubeZ_4-2"].geometry}
              material={materials["CubeZ_4-2 Material"]}
              castShadow
              receiveShadow
              position={[0, -16.5, 0]}
            />
            <mesh
              name="CubeZ_1-31"
              geometry={nodes["CubeZ_1-31"].geometry}
              material={materials["CubeZ_1-31 Material"]}
              castShadow
              receiveShadow
              position={[19.5, 16.5, 0]}
            />
            <mesh
              name="CubeZ_2-31"
              geometry={nodes["CubeZ_2-31"].geometry}
              material={materials["CubeZ_2-31 Material"]}
              castShadow
              receiveShadow
              position={[19.5, 6.1, 0]}
            />
            <mesh
              name="CubeZ_3-31"
              geometry={nodes["CubeZ_3-31"].geometry}
              material={materials["CubeZ_3-31 Material"]}
              castShadow
              receiveShadow
              position={[19.5, -5.2, 0]}
            />
            <mesh
              name="CubeZ_4-3"
              geometry={nodes["CubeZ_4-3"].geometry}
              material={materials["CubeZ_4-3 Material"]}
              castShadow
              receiveShadow
              position={[19.5, -16.5, 0]}
            />
          </group>
        </group>
      )}
      {useCamera && (
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={11.73}
          far={100000}
          near={-100000}
          position={[577.35, 577.35, 577.35]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
          scale={1}
        />
      )}
    </>
  );
}
