/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";
import { PALLETURL } from "../../constant/pallet";
import convertToWarehouseSize from "../../utilityFunc/convertToWarehouseSize";
import defaultPositionPallet from "../../utilityFunc/defaultPositionPallet";
import convertPosToReaclPos from "../../utilityFunc/convertPosToReaclPos";

export default function Pallet601524Scene({
  warehouseSize,
  useCamera,
  positionPallet,
}) {
  const { nodes, materials } = useSpline(PALLETURL);
  const size = convertToWarehouseSize(warehouseSize);
  const defPos = defaultPositionPallet(Object.values(size), [60, 15, 24]);
  const position = convertPosToReaclPos(positionPallet);
  return (
    <>
      {nodes && materials && (
        <group
          name="Pallet_60-15-24"
          position={[
            defPos[0] + position[0],
            defPos[1] + position[2],
            defPos[2] + position[1],
          ]}
        >
          <group name="GroupX" position={[0, 0.5, 0]}>
            <mesh
              name="CubeX_1-1"
              geometry={nodes["CubeX_1-1"].geometry}
              material={materials["CubeX_1-1 Material"]}
              castShadow
              receiveShadow
              position={[0, 11.5, -7]}
            />
            <mesh
              name="CubeX_1-2"
              geometry={nodes["CubeX_1-2"].geometry}
              material={materials["CubeX_1-2 Material"]}
              castShadow
              receiveShadow
              position={[0, 0, -7]}
            />
            <mesh
              name="CubeX_1-3"
              geometry={nodes["CubeX_1-3"].geometry}
              material={materials["CubeX_1-3 Material"]}
              castShadow
              receiveShadow
              position={[0, -11.5, -7]}
            />
            <mesh
              name="CubeX_2-1"
              geometry={nodes["CubeX_2-1"].geometry}
              material={materials["CubeX_2-1 Material"]}
              castShadow
              receiveShadow
              position={[0, 11.5, 0]}
            />
            <mesh
              name="CubeX_2-2"
              geometry={nodes["CubeX_2-2"].geometry}
              material={materials["CubeX_2-2 Material"]}
              castShadow
              receiveShadow
            />
            <mesh
              name="CubeX_2-3"
              geometry={nodes["CubeX_2-3"].geometry}
              material={materials["CubeX_2-3 Material"]}
              castShadow
              receiveShadow
              position={[0, -11.5, 0]}
            />
            <mesh
              name="CubeX_3-1"
              geometry={nodes["CubeX_3-1"].geometry}
              material={materials["CubeX_3-1 Material"]}
              castShadow
              receiveShadow
              position={[0, 11.5, 7]}
            />
            <mesh
              name="CubeX_3-2"
              geometry={nodes["CubeX_3-2"].geometry}
              material={materials["CubeX_3-2 Material"]}
              castShadow
              receiveShadow
              position={[0, 0, 7]}
            />
            <mesh
              name="CubeX_3-3"
              geometry={nodes["CubeX_3-3"].geometry}
              material={materials["CubeX_3-3 Material"]}
              castShadow
              receiveShadow
              position={[0, -11.5, 7]}
            />
          </group>
          <group name="GroupY" position={[0, -0.5, 0]}>
            <mesh
              name="CubeY_1-1"
              geometry={nodes["CubeY_1-1"].geometry}
              material={materials["CubeY_1-1 Material"]}
              castShadow
              receiveShadow
              position={[-29.5, 0, -7]}
            />
            <mesh
              name="CubeY_1-2"
              geometry={nodes["CubeY_1-2"].geometry}
              material={materials["CubeY_1-2 Material"]}
              castShadow
              receiveShadow
              position={[-10, 0, -7]}
            />
            <mesh
              name="CubeY_1-3"
              geometry={nodes["CubeY_1-3"].geometry}
              material={materials["CubeY_1-3 Material"]}
              castShadow
              receiveShadow
              position={[10, 0, -7]}
            />
            <mesh
              name="CubeY_1-4"
              geometry={nodes["CubeY_1-4"].geometry}
              material={materials["CubeY_1-4 Material"]}
              castShadow
              receiveShadow
              position={[29.5, 0, -7]}
            />
            <mesh
              name="CubeY_2-1 "
              geometry={nodes["CubeY_2-1 "].geometry}
              material={materials["CubeY_2-1  Material"]}
              castShadow
              receiveShadow
              position={[-29.5, 0, 7]}
            />
            <mesh
              name="CubeY_2-2"
              geometry={nodes["CubeY_2-2"].geometry}
              material={materials["CubeY_2-2 Material"]}
              castShadow
              receiveShadow
              position={[-10, 0, 7]}
            />
            <mesh
              name="CubeY_2-3"
              geometry={nodes["CubeY_2-3"].geometry}
              material={materials["CubeY_2-3 Material"]}
              castShadow
              receiveShadow
              position={[10, 0, 7]}
            />
            <mesh
              name="CubeY_2-4"
              geometry={nodes["CubeY_2-4"].geometry}
              material={materials["CubeY_2-4 Material"]}
              castShadow
              receiveShadow
              position={[29.5, 0, 7]}
            />
          </group>
          <group name="GroupZ" position={[0, 0.5, 0]}>
            <mesh
              name="CubeZ_1-1"
              geometry={nodes["CubeZ_1-1"].geometry}
              material={materials["CubeZ_1-1 Material"]}
              castShadow
              receiveShadow
              position={[-29.5, 11.5, 0]}
            />
            <mesh
              name="CubeZ_1-2"
              geometry={nodes["CubeZ_1-2"].geometry}
              material={materials["CubeZ_1-2 Material"]}
              castShadow
              receiveShadow
              position={[-10, 11.5, 0]}
            />
            <mesh
              name="CubeZ_1-3"
              geometry={nodes["CubeZ_1-3"].geometry}
              material={materials["CubeZ_1-3 Material"]}
              castShadow
              receiveShadow
              position={[10, 11.5, 0]}
            />
            <mesh
              name="CubeZ_1-4"
              geometry={nodes["CubeZ_1-4"].geometry}
              material={materials["CubeZ_1-4 Material"]}
              castShadow
              receiveShadow
              position={[29.5, 11.5, 0]}
            />
            <mesh
              name="CubeZ_2-1"
              geometry={nodes["CubeZ_2-1"].geometry}
              material={materials["CubeZ_2-1 Material"]}
              castShadow
              receiveShadow
              position={[-29.5, 0, 0]}
            />
            <mesh
              name="CubeZ_2-2"
              geometry={nodes["CubeZ_2-2"].geometry}
              material={materials["CubeZ_2-2 Material"]}
              castShadow
              receiveShadow
              position={[-10, 0, 0]}
            />
            <mesh
              name="CubeZ_2-3"
              geometry={nodes["CubeZ_2-3"].geometry}
              material={materials["CubeZ_2-3 Material"]}
              castShadow
              receiveShadow
              position={[10, 0, 0]}
            />
            <mesh
              name="CubeZ_2-4"
              geometry={nodes["CubeZ_2-4"].geometry}
              material={materials["CubeZ_2-4 Material"]}
              castShadow
              receiveShadow
              position={[29.5, 0, 0]}
            />
            <mesh
              name="CubeZ_3-1"
              geometry={nodes["CubeZ_3-1"].geometry}
              material={materials["CubeZ_3-1 Material"]}
              castShadow
              receiveShadow
              position={[-29.5, -11.5, 0]}
            />
            <mesh
              name="CubeZ_3-2"
              geometry={nodes["CubeZ_3-2"].geometry}
              material={materials["CubeZ_3-2 Material"]}
              castShadow
              receiveShadow
              position={[-10, -11.5, 0]}
            />
            <mesh
              name="CubeZ_3-3"
              geometry={nodes["CubeZ_3-3"].geometry}
              material={materials["CubeZ_3-3 Material"]}
              castShadow
              receiveShadow
              position={[10, -11.5, 0]}
            />
            <mesh
              name="CubeZ_3-4"
              geometry={nodes["CubeZ_3-4"].geometry}
              material={materials["CubeZ_3-4 Material"]}
              castShadow
              receiveShadow
              position={[29.5, -11.5, 0]}
            />
          </group>
        </group>
      )}
      {useCamera && (
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={11.73}
          far={100000}
          near={-100000}
          position={[577.35, 577.35, 577.35]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
          scale={1}
        />
      )}
    </>
  );
}
