/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/gyAiBUcZyAaZU5ae/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#fefefe']} />
      <group {...props} dispose={null}>
        <mesh
          name="Hang doc2 7"
          geometry={nodes['Hang doc2 7'].geometry}
          material={materials['Hang doc2 7 Material']}
          castShadow
          receiveShadow
          position={[200, 170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 71"
          geometry={nodes['Hang doc2 71'].geometry}
          material={materials['Hang doc2 71 Material']}
          castShadow
          receiveShadow
          position={[0, 170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 72"
          geometry={nodes['Hang doc2 72'].geometry}
          material={materials['Hang doc2 72 Material']}
          castShadow
          receiveShadow
          position={[-200, 170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 6"
          geometry={nodes['Hang doc2 6'].geometry}
          material={materials['Hang doc2 6 Material']}
          castShadow
          receiveShadow
          position={[200, 85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 61"
          geometry={nodes['Hang doc2 61'].geometry}
          material={materials['Hang doc2 61 Material']}
          castShadow
          receiveShadow
          position={[0, 85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 62"
          geometry={nodes['Hang doc2 62'].geometry}
          material={materials['Hang doc2 62 Material']}
          castShadow
          receiveShadow
          position={[-200, 85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 5"
          geometry={nodes['Hang doc2 5'].geometry}
          material={materials['Hang doc2 5 Material']}
          castShadow
          receiveShadow
          position={[200, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 51"
          geometry={nodes['Hang doc2 51'].geometry}
          material={materials['Hang doc2 51 Material']}
          castShadow
          receiveShadow
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 52"
          geometry={nodes['Hang doc2 52'].geometry}
          material={materials['Hang doc2 52 Material']}
          castShadow
          receiveShadow
          position={[-200, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 4"
          geometry={nodes['Hang doc2 4'].geometry}
          material={materials['Hang doc2 4 Material']}
          castShadow
          receiveShadow
          position={[200, -85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 41"
          geometry={nodes['Hang doc2 41'].geometry}
          material={materials['Hang doc2 41 Material']}
          castShadow
          receiveShadow
          position={[0, -85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 42"
          geometry={nodes['Hang doc2 42'].geometry}
          material={materials['Hang doc2 42 Material']}
          castShadow
          receiveShadow
          position={[-200, -85, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 3"
          geometry={nodes['Hang doc2 3'].geometry}
          material={materials['Hang doc2 3 Material']}
          castShadow
          receiveShadow
          position={[200, -170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2 2"
          geometry={nodes['Hang doc2 2'].geometry}
          material={materials['Hang doc2 2 Material']}
          castShadow
          receiveShadow
          position={[0, -170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang doc2"
          geometry={nodes['Hang doc2'].geometry}
          material={materials['Hang doc2 Material']}
          castShadow
          receiveShadow
          position={[-200, -170, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hang 8"
          geometry={nodes['Hang 8'].geometry}
          material={materials['Hang 8 Material']}
          castShadow
          receiveShadow
          position={[0, 170, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 81"
          geometry={nodes['Hang 81'].geometry}
          material={materials['Hang 81 Material']}
          castShadow
          receiveShadow
          position={[0, 85, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 82"
          geometry={nodes['Hang 82'].geometry}
          material={materials['Hang 82 Material']}
          castShadow
          receiveShadow
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 83"
          geometry={nodes['Hang 83'].geometry}
          material={materials['Hang 83 Material']}
          castShadow
          receiveShadow
          position={[0, -85, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 84"
          geometry={nodes['Hang 84'].geometry}
          material={materials['Hang 84 Material']}
          castShadow
          receiveShadow
          position={[0, -170, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 6"
          geometry={nodes['Hang 6'].geometry}
          material={materials['Hang 6 Material']}
          castShadow
          receiveShadow
          position={[0, 170, 75]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 61"
          geometry={nodes['Hang 61'].geometry}
          material={materials['Hang 61 Material']}
          castShadow
          receiveShadow
          position={[0, 85, 75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 62"
          geometry={nodes['Hang 62'].geometry}
          material={materials['Hang 62 Material']}
          castShadow
          receiveShadow
          position={[0, 0, 75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 63"
          geometry={nodes['Hang 63'].geometry}
          material={materials['Hang 63 Material']}
          castShadow
          receiveShadow
          position={[0, -85, 75]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 64"
          geometry={nodes['Hang 64'].geometry}
          material={materials['Hang 64 Material']}
          castShadow
          receiveShadow
          position={[0, -170, 75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 1"
          geometry={nodes['Hang 1'].geometry}
          material={materials['Hang 1 Material']}
          castShadow
          receiveShadow
          position={[0, 170, -75]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 2"
          geometry={nodes['Hang 2'].geometry}
          material={materials['Hang 2 Material']}
          castShadow
          receiveShadow
          position={[0, 85, -75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 3"
          geometry={nodes['Hang 3'].geometry}
          material={materials['Hang 3 Material']}
          castShadow
          receiveShadow
          position={[0, 0, -75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Hang 4"
          geometry={nodes['Hang 4'].geometry}
          material={materials['Hang 4 Material']}
          castShadow
          receiveShadow
          position={[0, -85, -75]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Hang 5"
          geometry={nodes['Hang 5'].geometry}
          material={materials['Hang 5 Material']}
          castShadow
          receiveShadow
          position={[0, -170, -75]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Cot 6"
          geometry={nodes['Cot 6'].geometry}
          material={materials['Cot 6 Material']}
          castShadow
          receiveShadow
          position={[-200, -10, 75]}
        />
        <mesh
          name="Cot 5"
          geometry={nodes['Cot 5'].geometry}
          material={materials['Cot 5 Material']}
          castShadow
          receiveShadow
          position={[0, -10, 75]}
        />
        <mesh
          name="Cot 4"
          geometry={nodes['Cot 4'].geometry}
          material={materials['Cot 4 Material']}
          castShadow
          receiveShadow
          position={[200, -10, 75]}
        />
        <mesh
          name="Cot 3"
          geometry={nodes['Cot 3'].geometry}
          material={materials['Cot 3 Material']}
          castShadow
          receiveShadow
          position={[200, -10, -75]}
        />
        <mesh
          name="Cot 2"
          geometry={nodes['Cot 2'].geometry}
          material={materials['Cot 2 Material']}
          castShadow
          receiveShadow
          position={[0, -10, -75]}
        />
        <mesh
          name="Cot 1"
          geometry={nodes['Cot 1'].geometry}
          material={materials['Cot 1 Material']}
          castShadow
          receiveShadow
          position={[-200, -10, -75]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={1}
          far={100000}
          near={-100000}
          position={[554.24, 628.01, 599.24]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
