/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { PerspectiveCamera } from "@react-three/drei";
import { WAREHOUSE3DURL } from "./../../constant/warehouse";
import convertToWarehouseSize from "../../utilityFunc/convertToWarehouseSize";

export default function Scene({ warehouseSize, useCamera }) {
  const { nodes, materials } = useSpline(WAREHOUSE3DURL);
  const size = convertToWarehouseSize(warehouseSize);
  const nameWarehouse = `warehouse_${size.x}-${size.z}-${size.y}`;
  return (
    <>
      {nodes && materials && (
        <>
          <mesh
            name={nameWarehouse}
            geometry={nodes[nameWarehouse].geometry}
            material={materials.warehouseMaterial}
            castShadow
            receiveShadow
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[46, -62, 76]}
          />
        </>
      )}
      {useCamera && (
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={5}
          fov={45}
          position={[344, 424, 488]}
          rotation={[-0.49, 0.46, 0.23]}
        />
      )}
    </>
  );
}
